# Generated by Django 2.2 on 2021-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
